namespace Model_Binding.Models
{
    public class Employee
    {
        public int EmpNo { get; set; }
        public string Name { get; set; }
        public decimal Basic { get; set; }
        public int DeptNo { get; set; }
    }
}
/*
 ->Build the project whenever you change something

 Scaffolding means the code that is generated by visual studio

 */